version: "2.1"
services:
  live-origin:
    image: unifiedstreaming/live:latest
    ports:
      - 80:80
    environment:
      - USP_LICENSE_KEY
      - CHANNEL=test
      - LOG_LEVEL=debug
      - PUB_POINT_OPTS=--archiving=1 --archive_length=3600 --archive_segment_length=1800 --dvr_window_length=30 --restart_on_encoder_reconnect --mpd.min_buffer_time=48/25 --mpd.suggested_presentation_delay=48/25 --hls.minimum_fragment_length=48/25 --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
  ffmpeg:
    build: ffmpeg
    environment:
      - FRAME_RATE=25
      - GOP_LENGTH=48
      - AUDIO_FRAG_DUR_MICROS=1920000
      - PUB_POINT_URI=http://live-origin/test/test.isml/
      - LOGO_OVERLAY=
    depends_on:
      live-origin:
        condition: service_healthy
