version: "2.1"
services:
  live-origin:
    image: unifiedstreaming/live:latest
    ports:
      - 80:80
    environment:
      - USP_LICENSE_KEY
      - CHANNEL=test
      - PUB_POINT_OPTS=--archiving=1 --archive_length=21600 --archive_segment_length=3600 --dvr_window_length=30 --restart_on_encoder_reconnect --mpd.min_buffer_time=1 --mpd.suggested_presentation_delay=1
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
  ffmpeg:
    build: ffmpeg
    environment:
      - FRAME_RATE=25
      - GOP_LENGTH=24
      - PUB_POINT_URI=http://live-origin/test/test.isml/
      - LOGO_OVERLAY=
    depends_on:
      live-origin:
        condition: service_healthy
