version: "2.1"
services:
  live-origin:
    image: unifiedstreaming/live:latest
    ports:
      - 80:80
    environment:
      - USP_LICENSE_KEY
      - CHANNEL=test
      - LOG_LEVEL=warn
      - PUB_POINT_OPTS=--archiving=1 --archive_length=3600 --archive_segment_length=1800 --dvr_window_length=30 --restart_on_encoder_reconnect --mpd.min_buffer_time=48/25 --mpd.suggested_presentation_delay=48/25 --hls.minimum_fragment_length=48/25 --mpd.minimum_fragment_length=48/25 --mpd.segment_template=time --hls.client_manifest_version=4
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
  ffmpeg:
    build: ffmpeg
    environment:
      # Video Codec Options: libx264 only
      # Audio Codec Options: aac only
      # Video Track 1 Setting (High)
      - V1_CODEC=libx264
      - V1_BITRATE=1000k
      - V1_FRAME_RATE=50
      - V1_GOP_LENGTH=96
      - V1_ASPECT_W=1280
      - V1_ASPECT_H=720
      # Video Track 2 Setting (Low)
      - V2_CODEC=libx264
      - V2_BITRATE=500k
      - V2_FRAME_RATE=25
      - V2_GOP_LENGTH=48
      - V2_ASPECT_W=1024
      - V2_ASPECT_H=576
      # Audio Track 1 (High)
      - A1_CODEC=aac
      - A1_BITRATE=128k
      - A1_LANGUAGE=eng
      # Audio Track 2 (Low)
      - A2_CODEC=aac
      - A2_BITRATE=64k
      - A2_LANGUAGE=dut
      # Shared Settings
      - AUDIO_FRAG_DUR_MICROS=1920000
      - PUB_POINT_URI=http://live-origin/test/test.isml
    depends_on:
      live-origin:
        condition: service_healthy
